name: Cross-platform build Java 17

    
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - arm64-aarch64

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run tests
        run: mvn test -Dtest=LiteClientParserTest,UtilsTest
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Upload artifact
        run: mkdir MyLocalTon && cp target/MyLocalTon.jar MyLocalTon
      - uses: actions/upload-artifact@v2
        with:
          name: MyLocalTon
          path: MyLocalTon
