name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - arm64-aarch64
      - test-release

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Upload artifact
        run: mkdir MyLocalTon && cp target/MyLocalTon.jar MyLocalTon
      - uses: actions/upload-artifact@v2
        with:
          name: MyLocalTon
          path: MyLocalTon

      - name: Read CHANGELOG.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG_BODY::$r"

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          release_name: MyLocalTon v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          body: |
            ${{ steps.read_release.outputs.CHANGELOG_BODY }}
          draft: false
          prerelease: true

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon.jar
          asset_name: MyLocalTon.jar
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true
