name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - arm64-aarch64
      - test-release-2
      - test-install4j

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build x86-64 with Maven
        run: mvn package -DskipTests

      - uses: luangong/setup-install4j@v0.1.0
        with:
          version: 10.0.3
          license: ${{ secrets.INSTALL4J }}
          cache: true
      - run: |
          install4jc --version