name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - arm64-aarch64
      - test-release-2
      - test-install4j

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # arm64
      - name: Build arm64-aarch64 with Maven
        run: |
          git fetch
          git checkout arm64-aarch64
          mvn clean package -DskipTests
      - name: Rename arm64 binary
        run: mv target/MyLocalTon.jar target/MyLocalTon_macos_arm64.jar

      - name: Build x86-64 with Maven
        run: |
          git checkout test-install4j
          ls -lart target/MyLocalTon_macos_arm64.jar
          mvn clean package -DskipTests

      - uses: luangong/setup-install4j@main
        with:
          version: 10.0.3
          license: ${{ secrets.INSTALL4J }}
          cache: true

      - name: Create installers x86-64
        run: |
          install4jc .github/workflows/config.install4j     

      - name: Create installers macos arm64
        run: |
          install4jc .github/workflows/config.arm64.install4j     

      - name: Read CHANGELOG.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG_BODY::$r"

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          release_name: MyLocalTon v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          body: |
            ${{ steps.read_release.outputs.CHANGELOG_BODY }}
          draft: false
          prerelease: true

      - name: Upload generic JAR x86-64 to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon.jar
          asset_name: MyLocalTon.jar
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload Ubuntu executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_unix_0_0_1.sh
          asset_name: MyLocalTon_unix_0_0_1.sh
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload Windows x86-64 executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_windows-x64_0_0_1.exe
          asset_name: MyLocalTon_windows-x64_0_0_1.exe
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload Debian package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_linux_0_0_1.deb
          asset_name: MyLocalTon_linux_0_0_1.deb
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload RPM package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_linux_0_0_1.rpm
          asset_name: MyLocalTon_linux_0_0_1.rpm
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload MacOS x86-64 dmg package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_macos_0_0_1.dmg
          asset_name: MyLocalTon_macos_x86_64_0_0_1.dmg
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload MacOS arm64 dmg package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_macos_arm64_0_0_1.dmg
          asset_name: MyLocalTon_macos_arm64_0_0_1.dmg
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true

      - name: Upload MacOS arm64 archive package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/MyLocalTon_macos_arm64_0_0_1.tgz
          asset_name: MyLocalTon_macos_arm64_0_0_1.tgz
          tag: v${{ github.run_number }}-${{ steps.myref.outputs.branch }}
          overwrite: true